[app]
id = "mockuphone-dev"

team = [
    # Allow GitHub Actions in your repo to deploy
    { gitHubRepositoryActions="oursky/mockuphone.com", access="deployer" },
    { gitHubRepositoryActions="pkong-ds/mockuphone.com", access="deployer" }
]


[app.deployments]
# ttl = "24h"
# access = []

[[app.sites]]
name = "main"

[site]
public = "dist"

# access = []
