name: CD

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - test-cd # dont run cd until pageship deployment with github OIDC token is resolved

jobs:
  cd:
    name: cd
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Set env to staging
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "production" ]]; then
            echo "ENV=production" >> $GITHUB_ENV
          fi
      - name: Build html
        run: npm run build
      - name: Deploy
        env:
          PAGESHIP_API: https://api.pages.oursky.app
        run: make deploy
